# Generated by Django 5.0 on 2024-07-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0002_remove_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booked',
            field=models.TextField(default='not booked yet'),
        ),
    ]
