# Generated by Django 5.0 on 2024-09-19 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0004_booking_bmanager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='bmanager',
        ),
    ]
