# Generated by Django 5.0 on 2024-07-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='isassigned',
            field=models.IntegerField(default=0),
        ),
    ]
