# Generated by Django 5.0 on 2024-07-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager_app', '0004_alter_manager_isassigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='isapproved',
            field=models.BooleanField(default=False),
        ),
    ]
